/* Train App — exercise catalogue.
 *
 * Each entry:
 *   id        stable slug (never change: sessions reference it)
 *   name      display name
 *   eq        equipment: barbell | dumbbell | cable | kettlebell | bodyweight | machine | band | cardio
 *   group     stat bucket: Chest | Back | Shoulders | Arms | Legs | Glutes | Core | Cardio
 *   target    specific muscle text for the detail sheet
 *   pattern   animation pattern (must exist in anim.js PATTERNS)
 *   rest      suggested rest in seconds
 *   uni       true if performed one side at a time
 *   type      'weight' (default, logs weight x reps) | 'bw' (reps, optional added weight)
 *             | 'time' (logs duration) | 'cardio' (duration + optional distance)
 *   tips      one-line coaching cue
 */

const EXERCISES = [

  /* ── BARBELL ─────────────────────────────────────────────────────── */
  { id:'bb-bench-press', name:'Barbell Bench Press', eq:'barbell', group:'Chest', target:'Pectorals, triceps, front delts', pattern:'benchPress', rest:180, tips:'Squeeze the shoulder blades down and back; touch mid-chest.' },
  { id:'bb-incline-press', name:'Barbell Incline Bench Press', eq:'barbell', group:'Chest', target:'Upper pectorals, front delts', pattern:'inclinePress', rest:180, tips:'Bench at 30°. Bar touches just below the collarbone.' },
  { id:'bb-decline-press', name:'Barbell Decline Bench Press', eq:'barbell', group:'Chest', target:'Lower pectorals', pattern:'declinePress', rest:150, tips:'Lock your legs in before unracking.' },
  { id:'bb-close-grip-bench', name:'Close-Grip Bench Press', eq:'barbell', group:'Arms', target:'Triceps, inner chest', pattern:'benchPress', rest:150, tips:'Hands shoulder-width. Keep elbows tucked to your sides.' },
  { id:'bb-floor-press', name:'Barbell Floor Press', eq:'barbell', group:'Chest', target:'Pectorals, triceps', pattern:'floorPress', rest:150, tips:'Pause when the triceps touch the floor.' },
  { id:'bb-overhead-press', name:'Barbell Overhead Press', eq:'barbell', group:'Shoulders', target:'Front & side delts, triceps', pattern:'overheadPress', rest:150, tips:'Squeeze glutes; move your head back as the bar passes.' },
  { id:'bb-push-press', name:'Barbell Push Press', eq:'barbell', group:'Shoulders', target:'Delts, triceps, legs', pattern:'overheadPress', rest:150, tips:'Short dip, explosive drive from the legs.' },
  { id:'bb-back-squat', name:'Barbell Back Squat', eq:'barbell', group:'Legs', target:'Quads, glutes, spinal erectors', pattern:'squat', rest:210, tips:'Brace hard, break at the hips and knees together.' },
  { id:'bb-front-squat', name:'Barbell Front Squat', eq:'barbell', group:'Legs', target:'Quads, upper back, core', pattern:'frontSquat', rest:210, tips:'Elbows high — that keeps the bar from rolling forward.' },
  { id:'bb-overhead-squat', name:'Overhead Squat', eq:'barbell', group:'Legs', target:'Quads, shoulders, core', pattern:'frontSquat', rest:180, tips:'Actively push up into the bar the whole way down.' },
  { id:'bb-zercher-squat', name:'Zercher Squat', eq:'barbell', group:'Legs', target:'Quads, core, upper back', pattern:'frontSquat', rest:180, tips:'Bar sits in the elbow crease. Stay upright.' },
  { id:'bb-box-squat', name:'Barbell Box Squat', eq:'barbell', group:'Legs', target:'Quads, glutes, hamstrings', pattern:'squat', rest:180, tips:'Sit back to the box, pause, then drive up.' },
  { id:'bb-deadlift', name:'Barbell Deadlift', eq:'barbell', group:'Back', target:'Full posterior chain', pattern:'deadlift', rest:240, tips:'Bar stays against the legs. Push the floor away.' },
  { id:'bb-sumo-deadlift', name:'Sumo Deadlift', eq:'barbell', group:'Legs', target:'Glutes, quads, adductors', pattern:'deadlift', rest:240, tips:'Wide stance, toes out, spread the floor.' },
  { id:'bb-rack-pull', name:'Rack Pull', eq:'barbell', group:'Back', target:'Traps, lats, erectors', pattern:'deadlift', rest:180, tips:'Set pins just below the knee. Heavier than a deadlift.' },
  { id:'bb-rdl', name:'Barbell Romanian Deadlift', eq:'barbell', group:'Legs', target:'Hamstrings, glutes', pattern:'rdl', rest:150, tips:'Soft knees, push the hips back — feel the stretch.' },
  { id:'bb-stiff-leg-dl', name:'Stiff-Leg Deadlift', eq:'barbell', group:'Legs', target:'Hamstrings, glutes', pattern:'rdl', rest:150, tips:'Legs near straight; stop when the back would round.' },
  { id:'bb-good-morning', name:'Good Morning', eq:'barbell', group:'Legs', target:'Hamstrings, erectors', pattern:'goodMorning', rest:150, tips:'Light weight. Hinge, do not squat.' },
  { id:'bb-bent-row', name:'Barbell Bent-Over Row', eq:'barbell', group:'Back', target:'Lats, rhomboids, rear delts', pattern:'row', rest:150, tips:'Torso ~45°. Pull to the belly button.' },
  { id:'bb-pendlay-row', name:'Pendlay Row', eq:'barbell', group:'Back', target:'Lats, mid-back', pattern:'row', rest:150, tips:'Bar rests on the floor each rep. Explode up.' },
  { id:'bb-upright-row', name:'Barbell Upright Row', eq:'barbell', group:'Shoulders', target:'Side delts, traps', pattern:'uprightRow', rest:90, tips:'Stop at chest height to keep the shoulders happy.' },
  { id:'bb-shrug', name:'Barbell Shrug', eq:'barbell', group:'Shoulders', target:'Trapezius', pattern:'shrug', rest:90, tips:'Straight up and down — no rolling.' },
  { id:'bb-curl', name:'Barbell Curl', eq:'barbell', group:'Arms', target:'Biceps', pattern:'curl', rest:90, tips:'Elbows pinned at your ribs. No swinging.' },
  { id:'bb-reverse-curl', name:'Barbell Reverse Curl', eq:'barbell', group:'Arms', target:'Brachialis, forearms', pattern:'curl', rest:90, tips:'Overhand grip, knuckles up throughout.' },
  { id:'bb-preacher-curl', name:'Barbell Preacher Curl', eq:'barbell', group:'Arms', target:'Biceps (short head)', pattern:'preacherCurl', rest:90, tips:'Do not fully lock out at the bottom.' },
  { id:'bb-skullcrusher', name:'Skullcrusher', eq:'barbell', group:'Arms', target:'Triceps', pattern:'skullcrusher', rest:90, tips:'Only the forearms move. Lower behind the head.' },
  { id:'bb-hip-thrust', name:'Barbell Hip Thrust', eq:'barbell', group:'Glutes', target:'Glutes, hamstrings', pattern:'hipThrust', rest:150, tips:'Tuck the chin, finish with a hard glute squeeze.' },
  { id:'bb-lunge', name:'Barbell Walking Lunge', eq:'barbell', group:'Legs', target:'Quads, glutes', pattern:'lunge', rest:150, tips:'Long stride, back knee lightly kisses the floor.' },
  { id:'bb-split-squat', name:'Barbell Bulgarian Split Squat', eq:'barbell', group:'Legs', target:'Quads, glutes', pattern:'lunge', rest:150, uni:true, tips:'Rear foot elevated. Front shin near vertical.' },
  { id:'bb-calf-raise', name:'Barbell Calf Raise', eq:'barbell', group:'Legs', target:'Calves', pattern:'calfRaise', rest:75, tips:'Pause a full second at the top of every rep.' },
  { id:'bb-power-clean', name:'Power Clean', eq:'barbell', group:'Legs', target:'Full body — posterior chain', pattern:'clean', rest:180, tips:'Explode at the hip, then drop fast under the bar.' },
  { id:'bb-clean-press', name:'Clean and Press', eq:'barbell', group:'Shoulders', target:'Full body', pattern:'clean', rest:180, tips:'One smooth movement from floor to overhead.' },
  { id:'bb-thruster', name:'Barbell Thruster', eq:'barbell', group:'Legs', target:'Full body', pattern:'thruster', rest:150, tips:'Squat and press are one continuous drive.' },
  { id:'bb-wrist-curl', name:'Barbell Wrist Curl', eq:'barbell', group:'Arms', target:'Forearm flexors', pattern:'curl', rest:60, tips:'Forearms on the bench, only the wrists move.' },

  /* ── DUMBBELL ────────────────────────────────────────────────────── */
  { id:'db-bench-press', name:'Dumbbell Bench Press', eq:'dumbbell', group:'Chest', target:'Pectorals, triceps', pattern:'benchPress', rest:150, tips:'Deeper stretch than a barbell — use the extra range.' },
  { id:'db-incline-press', name:'Dumbbell Incline Press', eq:'dumbbell', group:'Chest', target:'Upper pectorals', pattern:'inclinePress', rest:150, tips:'Bench at 30°. Do not let the dumbbells clash.' },
  { id:'db-decline-press', name:'Dumbbell Decline Press', eq:'dumbbell', group:'Chest', target:'Lower pectorals', pattern:'declinePress', rest:120, tips:'Keep control — the bottom position is the hard part.' },
  { id:'db-floor-press', name:'Dumbbell Floor Press', eq:'dumbbell', group:'Chest', target:'Pectorals, triceps', pattern:'floorPress', rest:120, tips:'Great shoulder-friendly pressing option.' },
  { id:'db-fly', name:'Dumbbell Chest Fly', eq:'dumbbell', group:'Chest', target:'Pectorals', pattern:'chestFly', rest:90, tips:'Slight elbow bend, held constant. Hug a barrel.' },
  { id:'db-incline-fly', name:'Incline Dumbbell Fly', eq:'dumbbell', group:'Chest', target:'Upper pectorals', pattern:'chestFly', rest:90, tips:'Stop the stretch at chest level — no deeper.' },
  { id:'db-pullover', name:'Dumbbell Pullover', eq:'dumbbell', group:'Chest', target:'Pectorals, lats, serratus', pattern:'pullover', rest:90, tips:'Ribs down. Feel the stretch across the ribcage.' },
  { id:'db-shoulder-press', name:'Dumbbell Shoulder Press', eq:'dumbbell', group:'Shoulders', target:'Front & side delts', pattern:'overheadPress', rest:120, tips:'Press slightly inward so the dumbbells meet up top.' },
  { id:'db-arnold-press', name:'Arnold Press', eq:'dumbbell', group:'Shoulders', target:'All three delt heads', pattern:'overheadPress', rest:120, tips:'Rotate palms from facing you to facing forward.' },
  { id:'db-lateral-raise', name:'Dumbbell Lateral Raise', eq:'dumbbell', group:'Shoulders', target:'Side delts', pattern:'lateralRaise', rest:75, tips:'Lead with the elbows, stop at shoulder height.' },
  { id:'db-front-raise', name:'Dumbbell Front Raise', eq:'dumbbell', group:'Shoulders', target:'Front delts', pattern:'frontRaise', rest:75, tips:'No momentum — lower slower than you lift.' },
  { id:'db-rear-delt-fly', name:'Dumbbell Rear Delt Fly', eq:'dumbbell', group:'Shoulders', target:'Rear delts, rhomboids', pattern:'rearDeltFly', rest:75, tips:'Hinge to near-parallel. Think "pull apart", not "lift".' },
  { id:'db-upright-row', name:'Dumbbell Upright Row', eq:'dumbbell', group:'Shoulders', target:'Side delts, traps', pattern:'uprightRow', rest:75, tips:'Elbows lead and stay above the wrists.' },
  { id:'db-shrug', name:'Dumbbell Shrug', eq:'dumbbell', group:'Shoulders', target:'Trapezius', pattern:'shrug', rest:75, tips:'Hold the top for a beat every rep.' },
  { id:'db-row', name:'Dumbbell Bent-Over Row', eq:'dumbbell', group:'Back', target:'Lats, mid-back', pattern:'row', rest:120, tips:'Drive the elbows past the ribs.' },
  { id:'db-one-arm-row', name:'One-Arm Dumbbell Row', eq:'dumbbell', group:'Back', target:'Lats, rhomboids', pattern:'row', rest:105, uni:true, tips:'Hand and knee on the bench. Do not twist the torso.' },
  { id:'db-renegade-row', name:'Renegade Row', eq:'dumbbell', group:'Back', target:'Lats, core', pattern:'plank', rest:105, tips:'Wide feet. Fight the urge to rotate.' },
  { id:'db-curl', name:'Dumbbell Biceps Curl', eq:'dumbbell', group:'Arms', target:'Biceps', pattern:'curl', rest:75, tips:'Supinate — turn the pinky up at the top.' },
  { id:'db-hammer-curl', name:'Hammer Curl', eq:'dumbbell', group:'Arms', target:'Brachialis, forearms', pattern:'curl', rest:75, tips:'Neutral grip throughout, like holding a hammer.' },
  { id:'db-incline-curl', name:'Incline Dumbbell Curl', eq:'dumbbell', group:'Arms', target:'Biceps (long head)', pattern:'curl', rest:75, tips:'Let the arms hang behind you for a bigger stretch.' },
  { id:'db-concentration-curl', name:'Concentration Curl', eq:'dumbbell', group:'Arms', target:'Biceps peak', pattern:'preacherCurl', rest:60, uni:true, tips:'Elbow braced on the inner thigh.' },
  { id:'db-kickback', name:'Dumbbell Triceps Kickback', eq:'dumbbell', group:'Arms', target:'Triceps', pattern:'kickback', rest:60, tips:'Upper arm stays parallel to the floor.' },
  { id:'db-overhead-tricep', name:'Overhead Dumbbell Extension', eq:'dumbbell', group:'Arms', target:'Triceps (long head)', pattern:'triOverhead', rest:75, tips:'Elbows point forward, not out to the sides.' },
  { id:'db-skullcrusher', name:'Dumbbell Skullcrusher', eq:'dumbbell', group:'Arms', target:'Triceps', pattern:'skullcrusher', rest:75, tips:'Neutral grip is easier on the elbows.' },
  { id:'db-goblet-squat', name:'Goblet Squat', eq:'dumbbell', group:'Legs', target:'Quads, glutes, core', pattern:'frontSquat', rest:120, tips:'Elbows inside the knees at the bottom.' },
  { id:'db-front-squat', name:'Dumbbell Front Squat', eq:'dumbbell', group:'Legs', target:'Quads, glutes', pattern:'frontSquat', rest:120, tips:'Dumbbells rest on the shoulders.' },
  { id:'db-lunge', name:'Dumbbell Lunge', eq:'dumbbell', group:'Legs', target:'Quads, glutes', pattern:'lunge', rest:105, tips:'Step out far enough that the front shin stays vertical.' },
  { id:'db-reverse-lunge', name:'Dumbbell Reverse Lunge', eq:'dumbbell', group:'Legs', target:'Glutes, quads', pattern:'lunge', rest:105, tips:'Stepping back is kinder to the knees.' },
  { id:'db-split-squat', name:'Dumbbell Bulgarian Split Squat', eq:'dumbbell', group:'Legs', target:'Quads, glutes', pattern:'lunge', rest:120, uni:true, tips:'Rear foot on a bench. Lean slightly forward for glutes.' },
  { id:'db-step-up', name:'Dumbbell Step-Up', eq:'dumbbell', group:'Legs', target:'Quads, glutes', pattern:'lunge', rest:105, uni:true, tips:'Drive through the heel on the box; do not push off the floor.' },
  { id:'db-rdl', name:'Dumbbell Romanian Deadlift', eq:'dumbbell', group:'Legs', target:'Hamstrings, glutes', pattern:'rdl', rest:120, tips:'Dumbbells graze the legs on the way down.' },
  { id:'db-deadlift', name:'Dumbbell Deadlift', eq:'dumbbell', group:'Legs', target:'Glutes, hamstrings, back', pattern:'deadlift', rest:120, tips:'Chest up, weight through the mid-foot.' },
  { id:'db-calf-raise', name:'Dumbbell Calf Raise', eq:'dumbbell', group:'Legs', target:'Calves', pattern:'calfRaise', rest:60, tips:'Full stretch at the bottom, full squeeze on top.' },
  { id:'db-farmers-walk', name:"Farmer's Walk", eq:'dumbbell', group:'Core', target:'Grip, traps, core', pattern:'carry', rest:120, type:'time', tips:'Tall posture, ribs down, small quick steps.' },
  { id:'db-thruster', name:'Dumbbell Thruster', eq:'dumbbell', group:'Legs', target:'Full body', pattern:'thruster', rest:120, tips:'Use the leg drive to start the press.' },
  { id:'db-side-bend', name:'Dumbbell Side Bend', eq:'dumbbell', group:'Core', target:'Obliques', pattern:'sideBend', rest:60, uni:true, tips:'One dumbbell only — the other side is the resistance.' },
  { id:'db-russian-twist', name:'Weighted Russian Twist', eq:'dumbbell', group:'Core', target:'Obliques', pattern:'russianTwist', rest:60, tips:'Rotate from the ribcage, not just the arms.' },

  /* ── CABLE ───────────────────────────────────────────────────────── */
  { id:'cb-chest-fly', name:'Cable Chest Fly', eq:'cable', group:'Chest', target:'Pectorals', pattern:'chestFly', rest:90, tips:'Constant tension — never let the stack touch down.' },
  { id:'cb-crossover', name:'Cable Crossover', eq:'cable', group:'Chest', target:'Inner & lower pectorals', pattern:'chestFly', rest:90, tips:'Cross the hands past each other at the finish.' },
  { id:'cb-press', name:'Standing Cable Press', eq:'cable', group:'Chest', target:'Pectorals, core', pattern:'overheadPress', rest:90, tips:'Split stance for a stable base.' },
  { id:'cb-lat-pulldown', name:'Lat Pulldown', eq:'cable', group:'Back', target:'Lats, biceps', pattern:'pulldown', rest:120, tips:'Pull the bar to the collarbone, chest proud.' },
  { id:'cb-close-pulldown', name:'Close-Grip Lat Pulldown', eq:'cable', group:'Back', target:'Lats, lower lats', pattern:'pulldown', rest:120, tips:'Neutral V-handle, elbows drive straight down.' },
  { id:'cb-reverse-pulldown', name:'Reverse-Grip Pulldown', eq:'cable', group:'Back', target:'Lats, biceps', pattern:'pulldown', rest:120, tips:'Underhand grip biases the lower lats.' },
  { id:'cb-straight-arm-pulldown', name:'Straight-Arm Pulldown', eq:'cable', group:'Back', target:'Lats', pattern:'straightArmPulldown', rest:90, tips:'Arms stay locked — the shoulders do the work.' },
  { id:'cb-seated-row', name:'Seated Cable Row', eq:'cable', group:'Back', target:'Mid-back, lats', pattern:'seatedRow', rest:120, tips:'Pull to the navel; do not rock backwards.' },
  { id:'cb-one-arm-row', name:'One-Arm Cable Row', eq:'cable', group:'Back', target:'Lats, rhomboids', pattern:'seatedRow', rest:90, uni:true, tips:'Let the shoulder stretch forward at the start.' },
  { id:'cb-face-pull', name:'Face Pull', eq:'cable', group:'Shoulders', target:'Rear delts, rotator cuff', pattern:'facePull', rest:75, tips:'Rope to the forehead, thumbs back at the finish.' },
  { id:'cb-lateral-raise', name:'Cable Lateral Raise', eq:'cable', group:'Shoulders', target:'Side delts', pattern:'lateralRaise', rest:75, uni:true, tips:'Cable from the low pulley behind your body.' },
  { id:'cb-front-raise', name:'Cable Front Raise', eq:'cable', group:'Shoulders', target:'Front delts', pattern:'frontRaise', rest:75, tips:'Tension stays on at the bottom, unlike dumbbells.' },
  { id:'cb-rear-delt-fly', name:'Cable Rear Delt Fly', eq:'cable', group:'Shoulders', target:'Rear delts', pattern:'rearDeltFly', rest:75, tips:'High pulleys, arms sweep out and back.' },
  { id:'cb-upright-row', name:'Cable Upright Row', eq:'cable', group:'Shoulders', target:'Side delts, traps', pattern:'uprightRow', rest:75, tips:'Rope attachment lets the wrists sit naturally.' },
  { id:'cb-shrug', name:'Cable Shrug', eq:'cable', group:'Shoulders', target:'Trapezius', pattern:'shrug', rest:60, tips:'Stand slightly back from the pulley.' },
  { id:'cb-curl', name:'Cable Curl', eq:'cable', group:'Arms', target:'Biceps', pattern:'curl', rest:75, tips:'Constant tension through the whole range.' },
  { id:'cb-rope-hammer-curl', name:'Rope Hammer Curl', eq:'cable', group:'Arms', target:'Brachialis, forearms', pattern:'curl', rest:75, tips:'Pull the rope ends apart at the top.' },
  { id:'cb-pushdown', name:'Triceps Pushdown', eq:'cable', group:'Arms', target:'Triceps', pattern:'triPushdown', rest:75, tips:'Elbows glued to the ribs; only the forearms move.' },
  { id:'cb-rope-pushdown', name:'Rope Triceps Pushdown', eq:'cable', group:'Arms', target:'Triceps (lateral head)', pattern:'triPushdown', rest:75, tips:'Spread the rope apart at the bottom.' },
  { id:'cb-overhead-tricep', name:'Cable Overhead Extension', eq:'cable', group:'Arms', target:'Triceps (long head)', pattern:'triOverhead', rest:75, tips:'Face away from the stack, split stance.' },
  { id:'cb-kickback', name:'Cable Triceps Kickback', eq:'cable', group:'Arms', target:'Triceps', pattern:'kickback', rest:60, uni:true, tips:'Lock the upper arm in place and extend.' },
  { id:'cb-woodchop', name:'Cable Woodchop', eq:'cable', group:'Core', target:'Obliques, core', pattern:'woodchop', rest:75, uni:true, tips:'Pivot the back foot; rotate through the hips.' },
  { id:'cb-crunch', name:'Cable Crunch', eq:'cable', group:'Core', target:'Rectus abdominis', pattern:'cableCrunch', rest:75, tips:'Kneel, curl the ribs to the pelvis. Hips stay still.' },
  { id:'cb-pull-through', name:'Cable Pull-Through', eq:'cable', group:'Glutes', target:'Glutes, hamstrings', pattern:'rdl', rest:90, tips:'Hinge back between the legs, then snap the hips forward.' },
  { id:'cb-glute-kickback', name:'Cable Glute Kickback', eq:'cable', group:'Glutes', target:'Glutes', pattern:'gluteKickback', rest:75, uni:true, tips:'Keep the standing leg soft; squeeze at the top.' },
  { id:'cb-hip-abduction', name:'Cable Hip Abduction', eq:'cable', group:'Glutes', target:'Glute medius', pattern:'gluteKickback', rest:60, uni:true, tips:'Lift the leg out to the side, toes forward.' },

  /* ── KETTLEBELL ──────────────────────────────────────────────────── */
  { id:'kb-swing', name:'Kettlebell Swing', eq:'kettlebell', group:'Glutes', target:'Glutes, hamstrings, core', pattern:'kbSwing', rest:90, tips:'A hinge, not a squat. The arms are just rope.' },
  { id:'kb-one-arm-swing', name:'One-Arm Kettlebell Swing', eq:'kettlebell', group:'Glutes', target:'Glutes, hamstrings, core', pattern:'kbSwing', rest:90, uni:true, tips:'Resist the rotation with your obliques.' },
  { id:'kb-goblet-squat', name:'Kettlebell Goblet Squat', eq:'kettlebell', group:'Legs', target:'Quads, glutes', pattern:'frontSquat', rest:105, tips:'Hold the horns at chest height, sit straight down.' },
  { id:'kb-front-squat', name:'Kettlebell Front Squat', eq:'kettlebell', group:'Legs', target:'Quads, core', pattern:'frontSquat', rest:105, tips:'Bells rest in the rack position on the forearms.' },
  { id:'kb-clean', name:'Kettlebell Clean', eq:'kettlebell', group:'Shoulders', target:'Full body', pattern:'clean', rest:105, tips:'Guide the bell around the wrist — do not let it flip and bang.' },
  { id:'kb-clean-press', name:'Kettlebell Clean and Press', eq:'kettlebell', group:'Shoulders', target:'Full body', pattern:'clean', rest:120, tips:'Pause in the rack before pressing.' },
  { id:'kb-snatch', name:'Kettlebell Snatch', eq:'kettlebell', group:'Shoulders', target:'Full body, power', pattern:'kbSwing', rest:120, uni:true, tips:'One movement from between the legs to overhead.' },
  { id:'kb-press', name:'Kettlebell Overhead Press', eq:'kettlebell', group:'Shoulders', target:'Delts, triceps', pattern:'overheadPress', rest:105, uni:true, tips:'Press around your head, not in front of it.' },
  { id:'kb-push-press', name:'Kettlebell Push Press', eq:'kettlebell', group:'Shoulders', target:'Delts, triceps, legs', pattern:'overheadPress', rest:105, tips:'Dip with the legs, then drive.' },
  { id:'kb-high-pull', name:'Kettlebell High Pull', eq:'kettlebell', group:'Shoulders', target:'Traps, delts, hips', pattern:'uprightRow', rest:90, tips:'Hip snap first, elbow high and back.' },
  { id:'kb-row', name:'Kettlebell Bent-Over Row', eq:'kettlebell', group:'Back', target:'Lats, mid-back', pattern:'row', rest:90, uni:true, tips:'Pull the bell to the hip pocket.' },
  { id:'kb-renegade-row', name:'Kettlebell Renegade Row', eq:'kettlebell', group:'Back', target:'Lats, core', pattern:'plank', rest:105, tips:'Widen the feet to stop the hips rotating.' },
  { id:'kb-deadlift', name:'Kettlebell Deadlift', eq:'kettlebell', group:'Legs', target:'Glutes, hamstrings', pattern:'deadlift', rest:105, tips:'A great way to groove the hinge before swinging.' },
  { id:'kb-rdl', name:'Kettlebell Romanian Deadlift', eq:'kettlebell', group:'Legs', target:'Hamstrings, glutes', pattern:'rdl', rest:105, tips:'Hips back, chest tall, bell close.' },
  { id:'kb-lunge', name:'Kettlebell Lunge', eq:'kettlebell', group:'Legs', target:'Quads, glutes', pattern:'lunge', rest:105, tips:'Front rack or suitcase hold, both work.' },
  { id:'kb-windmill', name:'Kettlebell Windmill', eq:'kettlebell', group:'Core', target:'Obliques, shoulders, hamstrings', pattern:'sideBend', rest:90, uni:true, tips:'Eyes on the bell overhead the whole time.' },
  { id:'kb-halo', name:'Kettlebell Halo', eq:'kettlebell', group:'Shoulders', target:'Shoulders, thoracic mobility', pattern:'halo', rest:60, tips:'Circle the bell close around the head. Ribs down.' },
  { id:'kb-turkish-getup', name:'Turkish Get-Up', eq:'kettlebell', group:'Core', target:'Full body, stability', pattern:'getup', rest:120, uni:true, tips:'Five slow positions up, five back down.' },
  { id:'kb-farmers-carry', name:'Kettlebell Farmer Carry', eq:'kettlebell', group:'Core', target:'Grip, traps, core', pattern:'carry', rest:105, type:'time', tips:'Squeeze the handles hard, walk tall.' },
  { id:'kb-suitcase-carry', name:'Suitcase Carry', eq:'kettlebell', group:'Core', target:'Obliques, grip', pattern:'carry', rest:90, uni:true, type:'time', tips:'One bell only. Refuse to lean.' },
  { id:'kb-floor-press', name:'Kettlebell Floor Press', eq:'kettlebell', group:'Chest', target:'Pectorals, triceps', pattern:'floorPress', rest:105, tips:'The bell sits behind the wrist, not on top of it.' },

  /* ── BODYWEIGHT ──────────────────────────────────────────────────── */
  { id:'bw-pushup', name:'Push-Up', eq:'bodyweight', group:'Chest', target:'Pectorals, triceps, core', pattern:'pushup', rest:75, type:'bw', tips:'Body in one straight line — squeeze the glutes.' },
  { id:'bw-wide-pushup', name:'Wide Push-Up', eq:'bodyweight', group:'Chest', target:'Outer pectorals', pattern:'pushup', rest:75, type:'bw', tips:'Hands wider than the shoulders.' },
  { id:'bw-diamond-pushup', name:'Diamond Push-Up', eq:'bodyweight', group:'Arms', target:'Triceps, inner chest', pattern:'pushup', rest:75, type:'bw', tips:'Index fingers and thumbs form a diamond.' },
  { id:'bw-decline-pushup', name:'Decline Push-Up', eq:'bodyweight', group:'Chest', target:'Upper pectorals', pattern:'pushup', rest:75, type:'bw', tips:'Feet elevated shifts load to the upper chest.' },
  { id:'bw-incline-pushup', name:'Incline Push-Up', eq:'bodyweight', group:'Chest', target:'Pectorals', pattern:'pushup', rest:60, type:'bw', tips:'Hands on a bench — the easiest regression.' },
  { id:'bw-pike-pushup', name:'Pike Push-Up', eq:'bodyweight', group:'Shoulders', target:'Front delts, triceps', pattern:'pikePushup', rest:90, type:'bw', tips:'Hips high, crown of the head to the floor.' },
  { id:'bw-handstand-pushup', name:'Handstand Push-Up', eq:'bodyweight', group:'Shoulders', target:'Delts, triceps', pattern:'pikePushup', rest:150, type:'bw', tips:'Use a wall until the balance is there.' },
  { id:'bw-dip', name:'Dip', eq:'bodyweight', group:'Chest', target:'Lower chest, triceps', pattern:'dip', rest:120, type:'bw', tips:'Lean forward for chest, stay upright for triceps.' },
  { id:'bw-bench-dip', name:'Bench Dip', eq:'bodyweight', group:'Arms', target:'Triceps', pattern:'dip', rest:75, type:'bw', tips:'Keep the hips close to the bench.' },
  { id:'bw-pullup', name:'Pull-Up', eq:'bodyweight', group:'Back', target:'Lats, biceps', pattern:'pullup', rest:150, type:'bw', tips:'Start from a dead hang, chin clears the bar.' },
  { id:'bw-chinup', name:'Chin-Up', eq:'bodyweight', group:'Back', target:'Lats, biceps', pattern:'pullup', rest:150, type:'bw', tips:'Underhand grip — more biceps than a pull-up.' },
  { id:'bw-wide-pullup', name:'Wide-Grip Pull-Up', eq:'bodyweight', group:'Back', target:'Lats (outer)', pattern:'pullup', rest:150, type:'bw', tips:'Wider grip, shorter range. Drive the elbows down.' },
  { id:'bw-inverted-row', name:'Inverted Row', eq:'bodyweight', group:'Back', target:'Mid-back, lats', pattern:'invertedRow', rest:105, type:'bw', tips:'Body rigid, pull the chest to the bar.' },
  { id:'bw-squat', name:'Bodyweight Squat', eq:'bodyweight', group:'Legs', target:'Quads, glutes', pattern:'squat', rest:60, type:'bw', tips:'Sit between the hips, heels down.' },
  { id:'bw-jump-squat', name:'Jump Squat', eq:'bodyweight', group:'Legs', target:'Quads, glutes, power', pattern:'squat', rest:90, type:'bw', tips:'Land soft, absorb through the hips.' },
  { id:'bw-pistol-squat', name:'Pistol Squat', eq:'bodyweight', group:'Legs', target:'Quads, glutes, balance', pattern:'squat', rest:120, uni:true, type:'bw', tips:'Hold a counterweight until the balance clicks.' },
  { id:'bw-wall-sit', name:'Wall Sit', eq:'bodyweight', group:'Legs', target:'Quads', pattern:'wallSit', rest:75, type:'time', tips:'Thighs parallel, back flat on the wall.' },
  { id:'bw-lunge', name:'Bodyweight Lunge', eq:'bodyweight', group:'Legs', target:'Quads, glutes', pattern:'lunge', rest:60, type:'bw', tips:'Both knees to 90°.' },
  { id:'bw-reverse-lunge', name:'Reverse Lunge', eq:'bodyweight', group:'Legs', target:'Glutes, quads', pattern:'lunge', rest:60, type:'bw', tips:'Step back and control the descent.' },
  { id:'bw-split-squat', name:'Split Squat', eq:'bodyweight', group:'Legs', target:'Quads, glutes', pattern:'lunge', rest:75, uni:true, type:'bw', tips:'Feet stay planted; move straight up and down.' },
  { id:'bw-step-up', name:'Step-Up', eq:'bodyweight', group:'Legs', target:'Quads, glutes', pattern:'lunge', rest:60, uni:true, type:'bw', tips:'Box height at or just below the knee.' },
  { id:'bw-glute-bridge', name:'Glute Bridge', eq:'bodyweight', group:'Glutes', target:'Glutes, hamstrings', pattern:'gluteBridge', rest:60, type:'bw', tips:'Posterior tilt first, then lift. Squeeze hard.' },
  { id:'bw-single-leg-bridge', name:'Single-Leg Glute Bridge', eq:'bodyweight', group:'Glutes', target:'Glutes', pattern:'gluteBridge', rest:60, uni:true, type:'bw', tips:'Hips stay perfectly level.' },
  { id:'bw-hip-thrust', name:'Bodyweight Hip Thrust', eq:'bodyweight', group:'Glutes', target:'Glutes', pattern:'hipThrust', rest:60, type:'bw', tips:'Shoulder blades on the bench, chin tucked.' },
  { id:'bw-nordic-curl', name:'Nordic Hamstring Curl', eq:'bodyweight', group:'Legs', target:'Hamstrings', pattern:'nordicCurl', rest:120, type:'bw', tips:'Lower as slowly as you can. Brutal — start assisted.' },
  { id:'bw-calf-raise', name:'Bodyweight Calf Raise', eq:'bodyweight', group:'Legs', target:'Calves', pattern:'calfRaise', rest:45, type:'bw', tips:'Off a step for the full stretch.' },
  { id:'bw-plank', name:'Plank', eq:'bodyweight', group:'Core', target:'Whole core', pattern:'plank', rest:60, type:'time', tips:'Squeeze glutes and quads; do not let the hips sag.' },
  { id:'bw-side-plank', name:'Side Plank', eq:'bodyweight', group:'Core', target:'Obliques', pattern:'sidePlank', rest:45, uni:true, type:'time', tips:'Stack the feet, drive the bottom hip up.' },
  { id:'bw-hollow-hold', name:'Hollow Body Hold', eq:'bodyweight', group:'Core', target:'Rectus abdominis', pattern:'hollowHold', rest:60, type:'time', tips:'Lower back pressed flat into the floor.' },
  { id:'bw-crunch', name:'Crunch', eq:'bodyweight', group:'Core', target:'Rectus abdominis', pattern:'crunch', rest:45, type:'bw', tips:'Curl the ribs down — do not yank the neck.' },
  { id:'bw-situp', name:'Sit-Up', eq:'bodyweight', group:'Core', target:'Rectus abdominis, hip flexors', pattern:'situp', rest:45, type:'bw', tips:'Roll up one vertebra at a time.' },
  { id:'bw-bicycle-crunch', name:'Bicycle Crunch', eq:'bodyweight', group:'Core', target:'Obliques, abs', pattern:'bicycleCrunch', rest:45, type:'bw', tips:'Slow and deliberate beats fast and sloppy.' },
  { id:'bw-leg-raise', name:'Lying Leg Raise', eq:'bodyweight', group:'Core', target:'Lower abs, hip flexors', pattern:'legRaise', rest:60, type:'bw', tips:'Hands under the hips, lower back stays down.' },
  { id:'bw-hanging-leg-raise', name:'Hanging Leg Raise', eq:'bodyweight', group:'Core', target:'Lower abs', pattern:'hangingLegRaise', rest:90, type:'bw', tips:'No swinging. Curl the pelvis up at the top.' },
  { id:'bw-knee-raise', name:'Hanging Knee Raise', eq:'bodyweight', group:'Core', target:'Lower abs', pattern:'hangingLegRaise', rest:75, type:'bw', tips:'The easier version — knees to chest.' },
  { id:'bw-russian-twist', name:'Russian Twist', eq:'bodyweight', group:'Core', target:'Obliques', pattern:'russianTwist', rest:45, type:'bw', tips:'Lean back to 45° and hold it.' },
  { id:'bw-ab-wheel', name:'Ab Wheel Rollout', eq:'bodyweight', group:'Core', target:'Whole core, lats', pattern:'abWheel', rest:90, type:'bw', tips:'Ribs down. Only roll as far as you can control.' },
  { id:'bw-mountain-climber', name:'Mountain Climber', eq:'bodyweight', group:'Core', target:'Core, hip flexors, cardio', pattern:'mountainClimber', rest:45, type:'bw', tips:'Hips stay low and level.' },
  { id:'bw-burpee', name:'Burpee', eq:'bodyweight', group:'Cardio', target:'Full body', pattern:'burpee', rest:75, type:'bw', tips:'Chest to floor, then jump and clap overhead.' },
  { id:'bw-jumping-jack', name:'Jumping Jack', eq:'bodyweight', group:'Cardio', target:'Full body', pattern:'jumpingJack', rest:30, type:'bw', tips:'A classic warm-up. Land on the balls of the feet.' },
  { id:'bw-high-knees', name:'High Knees', eq:'bodyweight', group:'Cardio', target:'Hip flexors, calves', pattern:'run', rest:30, type:'time', tips:'Knees above hip height, quick feet.' },
  { id:'bw-superman', name:'Superman', eq:'bodyweight', group:'Back', target:'Erectors, glutes', pattern:'superman', rest:45, type:'bw', tips:'Lift the chest and thighs together, pause on top.' },
  { id:'bw-back-extension', name:'Back Extension', eq:'bodyweight', group:'Back', target:'Erectors, glutes', pattern:'backExtension', rest:75, type:'bw', tips:'Extend to a straight line — no hyperextension.' },
  { id:'bw-bird-dog', name:'Bird Dog', eq:'bodyweight', group:'Core', target:'Core, erectors', pattern:'birdDog', rest:45, type:'bw', tips:'Opposite arm and leg. Balance a glass on your back.' },
  { id:'bw-dead-bug', name:'Dead Bug', eq:'bodyweight', group:'Core', target:'Deep core', pattern:'deadBug', rest:45, type:'bw', tips:'Exhale as the limbs extend; keep the back flat.' },
  { id:'bw-box-jump', name:'Box Jump', eq:'bodyweight', group:'Legs', target:'Quads, glutes, power', pattern:'squat', rest:120, type:'bw', tips:'Step down between reps — never rebound.' },

  /* ── MACHINE ─────────────────────────────────────────────────────── */
  { id:'mc-leg-press', name:'Leg Press', eq:'machine', group:'Legs', target:'Quads, glutes', pattern:'legPress', rest:150, tips:'Never lock the knees out hard at the top.' },
  { id:'mc-hack-squat', name:'Hack Squat', eq:'machine', group:'Legs', target:'Quads', pattern:'legPress', rest:150, tips:'Feet low on the platform hits the quads hardest.' },
  { id:'mc-leg-extension', name:'Leg Extension', eq:'machine', group:'Legs', target:'Quads', pattern:'legExtension', rest:90, tips:'Pause and squeeze at full extension.' },
  { id:'mc-leg-curl', name:'Lying Leg Curl', eq:'machine', group:'Legs', target:'Hamstrings', pattern:'legCurl', rest:90, tips:'Hips stay down on the pad.' },
  { id:'mc-seated-leg-curl', name:'Seated Leg Curl', eq:'machine', group:'Legs', target:'Hamstrings', pattern:'legCurl', rest:90, tips:'More hamstring stretch than the lying version.' },
  { id:'mc-chest-press', name:'Machine Chest Press', eq:'machine', group:'Chest', target:'Pectorals, triceps', pattern:'benchPress', rest:120, tips:'Handles level with the mid-chest.' },
  { id:'mc-shoulder-press', name:'Machine Shoulder Press', eq:'machine', group:'Shoulders', target:'Delts, triceps', pattern:'overheadPress', rest:120, tips:'Back flat against the pad.' },
  { id:'mc-pec-deck', name:'Pec Deck', eq:'machine', group:'Chest', target:'Pectorals', pattern:'chestFly', rest:90, tips:'Pause for a second with the handles together.' },
  { id:'mc-lat-pulldown', name:'Machine Lat Pulldown', eq:'machine', group:'Back', target:'Lats', pattern:'pulldown', rest:120, tips:'Lock the thigh pad down first.' },
  { id:'mc-seated-row', name:'Machine Seated Row', eq:'machine', group:'Back', target:'Mid-back, lats', pattern:'seatedRow', rest:120, tips:'Chest on the pad kills the cheating.' },
  { id:'mc-assisted-pullup', name:'Assisted Pull-Up', eq:'machine', group:'Back', target:'Lats, biceps', pattern:'pullup', rest:120, tips:'Drop the assistance a plate at a time.' },
  { id:'mc-calf-raise', name:'Machine Calf Raise', eq:'machine', group:'Legs', target:'Calves', pattern:'calfRaise', rest:75, tips:'Slow negative, two-second stretch at the bottom.' },
  { id:'mc-ab-crunch', name:'Machine Ab Crunch', eq:'machine', group:'Core', target:'Rectus abdominis', pattern:'cableCrunch', rest:75, tips:'Curl the torso; do not just pull with the arms.' },
  { id:'mc-hip-abduction', name:'Hip Abduction Machine', eq:'machine', group:'Glutes', target:'Glute medius', pattern:'gluteKickback', rest:60, tips:'Lean forward slightly to bias the glutes.' },
  { id:'mc-back-extension', name:'45° Back Extension', eq:'machine', group:'Back', target:'Erectors, glutes, hamstrings', pattern:'backExtension', rest:90, tips:'Hold a plate to the chest once bodyweight is easy.' },
  { id:'mc-smith-squat', name:'Smith Machine Squat', eq:'machine', group:'Legs', target:'Quads, glutes', pattern:'squat', rest:150, tips:'Feet slightly forward of the bar path.' },

  /* ── BAND ────────────────────────────────────────────────────────── */
  { id:'bd-pull-apart', name:'Band Pull-Apart', eq:'band', group:'Shoulders', target:'Rear delts, rhomboids', pattern:'rearDeltFly', rest:45, tips:'Perfect between pressing sets. Arms stay straight.' },
  { id:'bd-face-pull', name:'Band Face Pull', eq:'band', group:'Shoulders', target:'Rear delts, rotator cuff', pattern:'facePull', rest:45, tips:'Anchor at eye height, pull to the forehead.' },
  { id:'bd-row', name:'Band Row', eq:'band', group:'Back', target:'Mid-back, lats', pattern:'seatedRow', rest:60, tips:'Step back until there is tension at the start.' },
  { id:'bd-press', name:'Band Chest Press', eq:'band', group:'Chest', target:'Pectorals, triceps', pattern:'overheadPress', rest:60, tips:'Band behind the back, press forward.' },
  { id:'bd-lateral-raise', name:'Band Lateral Raise', eq:'band', group:'Shoulders', target:'Side delts', pattern:'lateralRaise', rest:45, tips:'Stand on the band for tension that builds.' },
  { id:'bd-curl', name:'Band Biceps Curl', eq:'band', group:'Arms', target:'Biceps', pattern:'curl', rest:45, tips:'Hardest at the top — squeeze there.' },
  { id:'bd-pushdown', name:'Band Triceps Pushdown', eq:'band', group:'Arms', target:'Triceps', pattern:'triPushdown', rest:45, tips:'Anchor high on a door or rack.' },
  { id:'bd-squat', name:'Band Squat', eq:'band', group:'Legs', target:'Quads, glutes', pattern:'squat', rest:60, tips:'Band across the shoulders, stand on the loop.' },
  { id:'bd-good-morning', name:'Band Good Morning', eq:'band', group:'Legs', target:'Hamstrings, glutes', pattern:'goodMorning', rest:60, tips:'Great warm-up before deadlifts.' },
  { id:'bd-glute-kickback', name:'Band Glute Kickback', eq:'band', group:'Glutes', target:'Glutes', pattern:'gluteKickback', rest:45, uni:true, tips:'Drive the heel straight back, hips square.' },

  /* ── CARDIO ──────────────────────────────────────────────────────── */
  { id:'cd-run', name:'Running', eq:'cardio', group:'Cardio', target:'Cardiovascular, legs', pattern:'run', rest:0, type:'cardio', tips:'Log the duration and distance.' },
  { id:'cd-treadmill', name:'Treadmill', eq:'cardio', group:'Cardio', target:'Cardiovascular, legs', pattern:'run', rest:0, type:'cardio', tips:'A 1% incline roughly matches running outdoors.' },
  { id:'cd-walk', name:'Walking', eq:'cardio', group:'Cardio', target:'Cardiovascular', pattern:'run', rest:0, type:'cardio', tips:'Underrated for recovery and daily volume.' },
  { id:'cd-cycle', name:'Cycling', eq:'cardio', group:'Cardio', target:'Cardiovascular, quads', pattern:'cycle', rest:0, type:'cardio', tips:'Saddle height: near-straight leg at the bottom.' },
  { id:'cd-row-erg', name:'Rowing Machine', eq:'cardio', group:'Cardio', target:'Full body, cardiovascular', pattern:'rowErg', rest:0, type:'cardio', tips:'Legs, then back, then arms. Reverse on the way in.' },
  { id:'cd-elliptical', name:'Elliptical', eq:'cardio', group:'Cardio', target:'Cardiovascular', pattern:'run', rest:0, type:'cardio', tips:'Low impact — good on sore knees.' },
  { id:'cd-stair-climber', name:'Stair Climber', eq:'cardio', group:'Cardio', target:'Cardiovascular, glutes', pattern:'run', rest:0, type:'cardio', tips:'Stand tall, do not hang off the rails.' },
  { id:'cd-jump-rope', name:'Jump Rope', eq:'cardio', group:'Cardio', target:'Calves, cardiovascular', pattern:'jumpRope', rest:45, type:'time', tips:'Small jumps, turn the rope from the wrists.' },
  { id:'cd-swim', name:'Swimming', eq:'cardio', group:'Cardio', target:'Full body, cardiovascular', pattern:'swim', rest:0, type:'cardio', tips:'Log the distance in metres.' },
];

const EQUIPMENT = [
  { id:'barbell',    label:'Barbell',    icon:'▬' },
  { id:'dumbbell',   label:'Dumbbell',   icon:'▪' },
  { id:'cable',      label:'Cable',      icon:'⌇' },
  { id:'kettlebell', label:'Kettlebell', icon:'◗' },
  { id:'bodyweight', label:'Bodyweight', icon:'☗' },
  { id:'machine',    label:'Machine',    icon:'⚙' },
  { id:'band',       label:'Band',       icon:'∿' },
  { id:'cardio',     label:'Cardio',     icon:'❤' },
];

const GROUPS = ['Chest', 'Back', 'Shoulders', 'Arms', 'Legs', 'Glutes', 'Core', 'Cardio'];

export { EXERCISES, EQUIPMENT, GROUPS };
